=== gaiasismondo/securiDN/securiDN/DN37/xml/dtd/IEtab.dtd
<!ELEMENT IEtab     (tool|formalism|filter)*>



<!ELEMENT tool   (extension)*>
<!ATTLIST tool
  name         ID        #REQUIRED
  description  CDATA     #REQUIRED
>
  
<!ELEMENT extension   EMPTY>
<!ATTLIST tool
  ext         CDATA     #REQUIRED
>



<!ELEMENT formalism   (import|export)*>
<!ATTLIST formalism
  description  CDATA     #REQUIRED
  path         CDATA     #REQUIRED
  allowSubFormalisms (yes|no)  "no"
>

<!ELEMENT import   (parameter)*>
<!ATTLIST import
  toolref      CDATA     #REQUIRED
  class        CDATA     #REQUIRED
>

<!ELEMENT export   (parameter)*>
<!ATTLIST export
  toolref      CDATA     #REQUIRED
  class        CDATA     #REQUIRED
>

<!ELEMENT parameter   EMPTY>
<!ATTLIST parameter
  type         (boolean|double|integer|string)     #REQUIRED
  value        CDATA     #REQUIRED
>

=== gaiasismondo/securiDN/securiDN/DN37/xml/config/IEtab.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE fdl SYSTEM "IEtab.dtd">
<IEtab>
	<tool name="GreatSPN" description="GreatSPN">
	  <extension ext="*.net"/>
	</tool>
	
	<tool name="DnQL" description="DrawNET Query Language">
	  <extension ext="*.dnql"/>
	</tool>

	<formalism description="Petri Nets" path="PetriNets/PN/PN.fdl" allowSubFormalisms="no">
		<import toolref="GreatSPN" class="drawnet/lib/filters/GSPNFilter" />
		<export toolref="GreatSPN" class="drawnet/lib/filters/GSPNFilter" />
	</formalism>
	
	<formalism descritpion="ALL" path="*" allowSubFormalism="yes">
		<import toolref="DnQL" class="drawnet/lib/filters/DnQLfilter" />
		<export toolref="DnQL" class="drawnet/lib/filters/DnQLfilter" />
	</formalism>
</IEtab>
