=== gaiasismondo/securiDN/securiDN/DN37/xml/dtd/solvers_db.dtd
<!ELEMENT solversDB ( solver* ) >

<!ELEMENT solver ( formalism, type, class, description?, command* , commandPath* , commandLine* , parameter* ) >

<!ELEMENT formalism ( #PCDATA ) >

<!ELEMENT type ( #PCDATA ) >

<!ELEMENT class ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT command ( #PCDATA ) >
<!ATTLIST command
          id CDATA #REQUIRED >

<!ELEMENT commandPath ( #PCDATA ) >
<!ATTLIST commandPath
          id CDATA #REQUIRED >

<!ELEMENT commandLine ( #PCDATA ) >
<!ATTLIST commandLine
          id CDATA #REQUIRED >

<!ELEMENT parameter ( #PCDATA ) >
<!ATTLIST parameter
          id CDATA #REQUIRED >

=== gaiasismondo/securiDN/securiDN/DN37/xml/config/solvers_db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE solversDB SYSTEM "solvers_db.dtd" >
<solversDB>
	<solver>
		<formalism>SecuriDN</formalism>
		<type>filter</type>
		<class>SolverFilterSecuriDN</class>
	</solver>
	<solver>
		<formalism>SecuriDN</formalism>
		<type>filter</type>
		<class>SolverFilterAGimport</class>
	</solver>
	<solver>
		<formalism>SecuriDN</formalism>
		<type>filter</type>
		<class>SolverFilterAGexport</class>
	</solver>
	<solver>
		<formalism>SecuriDN</formalism>
		<type>filter</type>
		<class>SolverFilterDBN2</class>
	</solver>
	<solver>
		<formalism>SecuriDN</formalism>
		<type>filter</type>
		<class>SolverFilterAG</class>
	</solver>
	<solver>
		<formalism>DBN</formalism>
		<type>filter</type>
		<class>SolverFilterDBN</class>
	</solver>
</solversDB>
